### PR TITLE
Further adjustsments

### PR DESCRIPTION
**Pull request by eHanseFrank**
- tried to remove some filter, take a look at my view product_template_search_view_m2, the invisible attribute does not work. 
- added some filter
- added a method that casts qty_available (On Hand, which we are using in list price update, too) to integer
because qty_local_stock was somehow not working, I believe
- added some filter

### CODE REVIEW

**Comment by yostashiro** [comment]
@eHanseFrank This branch `fix-product-offer` does not keep the latest set of code, so I'd suggest you create PRs to the master branch of https://github.com/rfhk/awo-custom (`add-rmb-rate` has been an exception as it currently keeps the code that is semi-latest).

Please avoid including the code bits that do not work.  You can just send me questions with a link to your repository so that I will take a look.  Please try keeping the PRs as clean as possible.

**Comment by eHanseFrank** [comment]
Hi Yoshi,

so i will not make an PR as soon as there obvious problems with the 
code. Here take a look, two of the filters are not working. As their 
names suggest, they are supposed to show ultimately the same as 
quants(internal location) and quants(internal location) + overseas.

https://github.com/eHanseFrank/awo-custom/commit/cf66a308e7a8c8c06a4b814cadf9d1a9d4926db0#diff-f95d548c88c4e34db9628689e4fd6695

Please take a look.

Regards

Frank


Am 21-03-2017 um 9:41 PM schrieb Yoshi Tashiro:

**Comment by yostashiro** [comment]
@eHanseFrank Regarding the domains that are not working, you need to remove quotations from `'0'` to make the tuple `('qty_local_stock','&gt;',0)`.  You do not use quotations for integer/float fields.

**Comment by eHanseFrank** [comment]
Hi Yoshi,

I have changed it on test server but it is still not working. Maybe it 
has to do with the casting of qty_local_stock. Your filter is still 
working, even though it depends and that field via _get_local_stock. 
Please take a look.

https://github.com/eHanseFrank/awo-custom/blob/further_adjustsments/product_offer/models/product_template.py

Am 22-03-2017 um 10:42 PM schrieb Yoshi Tashiro:

**Comment by yostashiro** [comment]
@eHanseFrank It's a bit hard to keep track on your changes.  Can you please explain to me the details in our call which I suggested in another ticket for tomorrow 10:30.

**Pull request closed without merging**
